### PR TITLE
fixing several issues for submission

### LINKED ISSUE #73: change account linking to amazon oauth

### PR DESCRIPTION
**Pull request by fabsi88**
close #73 #61

### CODE REVIEW

File: src/d/alexa-openwebif/source/intents/remotecontrol.d [hunk 1]
```diff
@@ -63,9 +66,10 @@ final class IntentRCPrevious : BaseIntent
 	///
 	override AlexaResult onIntent(AlexaEvent, AlexaContext)
 	{
-		auto result = doRCIntent("Previous",apiClient,this);	
+		AlexaResult result;
 		result.response.card.title = getText(TextId.RCPreviousCardTitle);
 		result.response.card.content = getText(TextId.RCPreviousCardContent);
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/remotecontrol.d]: if setting result after this anyway these two lines have no effect

File: src/d/alexa-openwebif/source/intents/togglemute.d [hunk 2]
```diff
@@ -20,9 +22,18 @@ final class IntentToggleMute : BaseIntent
...
-
 		AlexaResult result;
+		Vol res;
+		try
+		{
+			res = apiClient.vol("mute");
+		}
+		catch (Exception e)
+		{
+			result = returnError(this);
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/togglemute.d]: why first set result if you return it anyway ? lets make this a oneliner (applies to all other intents aswell)

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 3]
```diff
@@ -26,10 +27,20 @@ final class IntentZapTo : BaseIntent
 		auto targetChannel = event.request.intent.slots["targetChannel"].value;
 		Subservice matchedServices;
 		auto switchedTo = getText(TextId.ZapFailedSSML);
+		AlexaResult result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: pulling up definition of result is also not necessary in any case when not uselessly setting result with the return of `returnError`

File: src/d/alexa-openwebif/source/skill.d [hunk 4]
```diff
@@ -161,6 +161,29 @@ final class OpenWebifSkill : AlexaSkill!OpenWebifSkill
 		assert(resp.response.card.type != AlexaCard.Type.LinkAccount);
 		assert(canFind(resp.response.card.content, "foobar123"));
 	}
+
+	///
+	bool runAmazonLogin(string _accessToken)
+	{
+	if (_accessToken.length == 0)
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/skill.d]: tab missing - auto format on save enabled ?

File: src/d/alexa-openwebif/source/skill.d [hunk 5]
```diff
@@ -161,6 +161,29 @@ final class OpenWebifSkill : AlexaSkill!OpenWebifSkill
...
+		else
+		{
+			amazonLoginApi = amazonLoginApiFactory(_accessToken);
+
+			import std.stdio : stderr;
+
+			try
+				immutable tokenInfo = amazonLoginApi.tokeninfo(_accessToken);
+			catch (Exception e)
+				stderr.writefln("tokenInfo parsing error: %s", e);
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/skill.d]: in case of an exception this method still returns true?

File: src/d/alexa-openwebif/source/skill.d [hunk 6]
```diff
@@ -190,3 +213,18 @@ unittest
...
 }
+
+AlexaResult returnError(ITextManager texts)
+{
+	import std.format : format;
+	import std.random : uniform;
+	import std.conv : to;
+
+	AlexaResult result;
+	auto errorId = uniform!uint();
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/skill.d]: WT fucking F ?!

File: src/d/alexa-openwebif/source/intents/remotecontrol.d (hunk 1 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/intents/remotecontrol.d]: !? don't get it. This is neccessary because the error functions sets the card title and content. So I need to define `AlexaResult result` first, set the "normal" card titles and make the api call with the nested error check. On error the `doRCIntent()` function returns a `AlexaResult` object with Error Card Title and Content. In case of no error it only returns the SSML.

File: src/d/alexa-openwebif/source/intents/togglemute.d (hunk 2 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/intents/togglemute.d]: It is planned to extend these `catch()` blocks with `stderr` outputs which should contain information of the `returnError()` function. So the step is neccessary. I've opened #76 for this

File: src/d/alexa-openwebif/source/skill.d (hunk 6 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/skill.d]: The user gets a error card with this error ID in the card content and instructions to open a ticket at github with this reference. So it is easier for us to find the error in cloudwatch and provide better help - see pic for bette explanation ;-)
image

File: src/d/alexa-openwebif/source/intents/zap.d (hunk 3 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/intents/zap.d]: fixed

File: src/d/alexa-openwebif/source/skill.d (hunk 4 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/skill.d]: fixed

File: src/d/alexa-openwebif/source/skill.d (hunk 5 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/skill.d]: fixed

File: src/d/alexa-openwebif/source/intents/remotecontrol.d [hunk 7]
```diff
@@ -75,16 +79,34 @@ final class IntentRCPrevious : BaseIntent
...
 		AlexaResult result;
+		About boxinfo;
+		try 
+		{
+			boxinfo = apiClient.about();
+		}
+		catch (Exception e)
+		{
+			result = returnError(texts);
+			return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/remotecontrol.d]: dito

File: src/d/alexa-openwebif/source/intents/remotecontrol.d [hunk 8]
```diff
@@ -75,16 +79,34 @@ final class IntentRCPrevious : BaseIntent
...
+			Remotecontrol rc;
+			// is needed because an call on about doesn't need authorization - this one does - so catch auth errors
+			try 
+			{
+				rc = apiClient.remotecontrol(code);
+			}
+			catch(Exception e)
+			{
+				result = returnError(texts);
+				return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/remotecontrol.d]: dito

File: src/d/alexa-openwebif/source/intents/services.d [hunk 9]
```diff
@@ -22,10 +23,17 @@ final class IntentServices : BaseIntent
...
+		ServicesList serviceList;
 		AlexaResult result;
+		try
+		{
+			serviceList = removeMarkers(apiClient.getallservices());
+		}
+		catch (Exception e)
+		{
+			result = returnError(this);
+			return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/services.d]: dito

File: src/d/alexa-openwebif/source/intents/sleeptimer.d [hunk 10]
```diff
@@ -21,15 +24,24 @@ final class IntentSleepTimer : BaseIntent
...
-			auto sleepTimer = apiClient.sleeptimer("get","standby",0, "False");
+			SleepTimer sleepTimer;
+			try
+			{
+				sleepTimer = apiClient.sleeptimer("get","standby",0, "False");
+			}
+			catch (Exception e)
+			{
+				result = returnError(this);
+				return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/sleeptimer.d]: dito

File: src/d/alexa-openwebif/source/intents/togglestandby.d [hunk 11]
```diff
@@ -20,9 +22,18 @@ final class IntentToggleStandby : BaseIntent
...
 		AlexaResult result;
+		PowerState res;
+		try
+		{
+			res = apiClient.powerstate(0);
+		}
+		catch (Exception e)
+		{
+			result = returnError(this);
+			return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/togglestandby.d]: dito

File: src/d/alexa-openwebif/source/intents/volume.d [hunk 12]
```diff
@@ -59,20 +60,33 @@ final class IntentSetVolume : BaseIntent
...
-			auto res = apiClient.vol("set"~to!string(targetVolume));
+			Vol res;
+			try 
+			{
+				res = apiClient.vol("set"~to!string(targetVolume));
+			} 
+			catch (Exception e)
+			{
+				result = returnError(this);
+				return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/volume.d]: dito

File: src/d/alexa-openwebif/source/intents/volume.d [hunk 13]
```diff
@@ -87,9 +101,18 @@ static AlexaResult doVolumeIntent(bool increase, OpenWebifApi apiClient, ITextMa
...
 	AlexaResult result;
+	Vol res;
+	try
+	{
+		res = apiClient.vol(action);
+	}
+	catch (Exception e)
+	{
+		result = returnError(texts);
+		return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/volume.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 14]
```diff
@@ -29,7 +30,16 @@ final class IntentZapTo : BaseIntent
...
-			auto allservices = removeMarkers(apiClient.getallservices());
+			ServicesList allservices;
+			try 
+			{
+				allservices = removeMarkers(apiClient.getallservices());
+			}
+			catch (Exception e)
+			{
+				auto result = returnError(this);
+				return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 15]
```diff
@@ -62,9 +72,10 @@ final class IntentZapUp : BaseIntent
 	///
 	override AlexaResult onIntent(AlexaEvent, AlexaContext)
 	{
-		auto result = doZapIntent(true, apiClient, this);
+		AlexaResult result;
 		result.response.card.title = getText(TextId.ZapUpCardTitle);
 		result.response.card.content = getText(TextId.ZapUpCardContent);
+		result = doZapIntent(true, apiClient, this);
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 16]
```diff
@@ -84,9 +95,10 @@ final class IntentZapDown : BaseIntent
 	///
 	override AlexaResult onIntent(AlexaEvent, AlexaContext)
 	{
-		auto result = doZapIntent(false, apiClient, this);
+		AlexaResult result;
 		result.response.card.title = getText(TextId.ZapDownCardTitle);
 		result.response.card.content = getText(TextId.ZapDownCardContent);
+		result = doZapIntent(false, apiClient, this);
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 17]
```diff
@@ -109,16 +121,26 @@ final class IntentZapRandom : BaseIntent
 		import std.format : format;
 
 		Subservice matchedServices;
+		AlexaResult result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 18]
```diff
@@ -109,16 +121,26 @@ final class IntentZapRandom : BaseIntent
...
 		auto switchedTo = getText(TextId.ZapFailedSSML);
-		auto allservices = removeMarkers(apiClient.getallservices());
+		try
+		{
+			allservices = removeMarkers(apiClient.getallservices());
+		}
+		catch (Exception e)
+		{
+			result = returnError(this);
+			return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 19]
```diff
@@ -147,7 +169,19 @@ final class IntentZapToEvent : BaseIntent
...
+		AlexaResult result;
+		
+		try
+		{
+			eventList = apiClient.epgsearch(targetEvent);
+		}
+		catch (Exception e)
+		{
+			result = returnError(this);
+			return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 20]
```diff
@@ -192,16 +225,26 @@ static AlexaResult doZapIntent(bool up, OpenWebifApi apiClient, ITextManager tex
 	import std.format : format;
 
 	Subservice matchedServices;
+	AlexaResult result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/intents/zap.d [hunk 21]
```diff
@@ -192,16 +225,26 @@ static AlexaResult doZapIntent(bool up, OpenWebifApi apiClient, ITextManager tex
...
 	auto switchedTo = texts.getText(TextId.ZapFailedSSML);
-	auto allservices = removeMarkers(apiClient.getallservices());
+	try
+	{
+		allservices = removeMarkers(apiClient.getallservices());
+	}
+	catch (Exception e)
+	{
+		result = returnError(texts);
+		return result;
```
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/intents/zap.d]: dito

File: src/d/alexa-openwebif/source/skill.d (hunk 6 above)
Comment (Extrawurst) [inline src/d/alexa-openwebif/source/skill.d]: lets atleast present this id to the user as a hexstring for the sake of readability

File: src/d/alexa-openwebif/source/intents/zap.d (hunk 17 above)
Comment (fabsi88) [inline src/d/alexa-openwebif/source/intents/zap.d]: negative dito
